/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Trip = IDL.Record({
  'id' : IDL.Text,
  'direction' : IDL.Text,
  'sideName' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'weightTons' : IDL.Float64,
  'dieselLiters' : IDL.Float64,
  'defLiters' : IDL.Float64,
  'sideId' : IDL.Text,
  'incomeCalculated' : IDL.Float64,
  'vehicleId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Side = IDL.Record({
  'id' : IDL.Text,
  'lead' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'upRate' : IDL.Float64,
  'downRate' : IDL.Float64,
});
export const Vehicle = IDL.Record({
  'id' : IDL.Text,
  'ownerName' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'createdAt' : Time,
  'passwordHash' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'vehicleId' : IDL.Opt(IDL.Text),
});
export const SideName = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const LoginResult = IDL.Record({
  'success' : IDL.Bool,
  'vehicleId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTrip' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [Trip],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSide' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
      [Side],
      [],
    ),
  'createVehicle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Vehicle], []),
  'deleteSide' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTrip' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteVehicle' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyTrips' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
  'getMyVehicle' : IDL.Func([IDL.Text], [Vehicle], ['query']),
  'getSideNames' : IDL.Func([], [IDL.Vec(SideName)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSides' : IDL.Func([], [IDL.Vec(Side)], ['query']),
  'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'loginCustomer' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], ['query']),
  'resetVehiclePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSide' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
      [Side],
      [],
    ),
  'updateTrip' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [Trip],
      [],
    ),
  'updateVehicle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Vehicle], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Trip = IDL.Record({
    'id' : IDL.Text,
    'direction' : IDL.Text,
    'sideName' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'weightTons' : IDL.Float64,
    'dieselLiters' : IDL.Float64,
    'defLiters' : IDL.Float64,
    'sideId' : IDL.Text,
    'incomeCalculated' : IDL.Float64,
    'vehicleId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Side = IDL.Record({
    'id' : IDL.Text,
    'lead' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'upRate' : IDL.Float64,
    'downRate' : IDL.Float64,
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Text,
    'ownerName' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'createdAt' : Time,
    'passwordHash' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'vehicleId' : IDL.Opt(IDL.Text),
  });
  const SideName = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const LoginResult = IDL.Record({
    'success' : IDL.Bool,
    'vehicleId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTrip' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [Trip],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSide' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
        [Side],
        [],
      ),
    'createVehicle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Vehicle], []),
    'deleteSide' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTrip' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteVehicle' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyTrips' : IDL.Func([IDL.Text], [IDL.Vec(Trip)], ['query']),
    'getMyVehicle' : IDL.Func([IDL.Text], [Vehicle], ['query']),
    'getSideNames' : IDL.Func([], [IDL.Vec(SideName)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSides' : IDL.Func([], [IDL.Vec(Side)], ['query']),
    'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'loginCustomer' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], ['query']),
    'resetVehiclePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSide' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
        [Side],
        [],
      ),
    'updateTrip' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [Trip],
        [],
      ),
    'updateVehicle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Vehicle], []),
  });
};

export const init = ({ IDL }) => { return []; };