/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LoginResult { 'success' : boolean, 'vehicleId' : string }
export interface Side {
  'id' : string,
  'lead' : bigint,
  'name' : string,
  'isActive' : boolean,
  'upRate' : number,
  'downRate' : number,
}
export interface SideName { 'id' : string, 'name' : string }
export type Time = bigint;
export interface Trip {
  'id' : string,
  'direction' : string,
  'sideName' : string,
  'date' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'weightTons' : number,
  'dieselLiters' : number,
  'defLiters' : number,
  'sideId' : string,
  'incomeCalculated' : number,
  'vehicleId' : string,
}
export interface UserProfile { 'name' : string, 'vehicleId' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : string,
  'ownerName' : string,
  'vehicleNumber' : string,
  'createdAt' : Time,
  'passwordHash' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTrip' : ActorMethod<
    [string, string, string, number, number, number, string],
    Trip
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSide' : ActorMethod<[string, bigint, number, number], Side>,
  'createVehicle' : ActorMethod<[string, string, string], Vehicle>,
  'deleteSide' : ActorMethod<[string], boolean>,
  'deleteTrip' : ActorMethod<[string], boolean>,
  'deleteVehicle' : ActorMethod<[string], boolean>,
  'getAllTrips' : ActorMethod<[], Array<Trip>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyTrips' : ActorMethod<[string], Array<Trip>>,
  'getMyVehicle' : ActorMethod<[string], Vehicle>,
  'getSideNames' : ActorMethod<[], Array<SideName>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listSides' : ActorMethod<[], Array<Side>>,
  'listVehicles' : ActorMethod<[], Array<Vehicle>>,
  'loginCustomer' : ActorMethod<[string, string], LoginResult>,
  'resetVehiclePassword' : ActorMethod<[string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSide' : ActorMethod<[string, string, bigint, number, number], Side>,
  'updateTrip' : ActorMethod<
    [string, string, string, number, number, number, string],
    Trip
  >,
  'updateVehicle' : ActorMethod<[string, string, string], Vehicle>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];